# Generated by Django 5.2.4 on 2025-08-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_income', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_score', models.IntegerField(default=0)),
                ('months_employed', models.IntegerField(default=0)),
                ('num_credit_lines', models.IntegerField(default=0)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('loan_term', models.IntegerField(default=0)),
                ('dti_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('education', models.CharField(default='High School', max_length=20)),
                ('employment_type', models.CharField(default='Full-Time', max_length=20)),
                ('marital_status', models.CharField(default='Single', max_length=20)),
                ('other_loans', models.BooleanField(default=False)),
                ('total_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_mortgage', models.BooleanField(default=False)),
                ('total_mortgage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_dependents', models.BooleanField(default=False)),
                ('loan_purpose', models.CharField(default='Other', max_length=20)),
                ('has_cosigner', models.BooleanField(default=False)),
                ('verification_passkey', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(default='Judging', max_length=10)),
                ('request_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelTrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
